/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/app/components/widgets/AppLogo.vue')['default']
    Button: typeof import('./src/app/components/Button/Button.vue')['default']
    ButtonGroup: typeof import('./src/app/components/Button/ButtonGroup.vue')['default']
    Input: typeof import('./src/app/components/Input.vue')['default']
    Notification: typeof import('./src/app/components/NotificationItem.vue')['default']
    NotificationItem: typeof import('./src/app/components/NotificationItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/app/components/Sidebar/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/app/components/Sidebar/SidebarItem.vue')['default']
    Toolbar: typeof import('./src/app/components/Toolbar/Toolbar.vue')['default']
    TreeView: typeof import('./src/app/components/TreeView/TreeView.vue')['default']
    TreeViewItem: typeof import('./src/app/components/TreeView/TreeViewItem.vue')['default']
  }
}
